config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'static/about' => 'home#about', as: :about

  resources :dogs, only: %i[index show create] do
    resources :posts, only: %i[index show create]
  end

  resource :timeline

  devise_for :users

  root 'home#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :user
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :dog, touch: true

  scope :most_recent_first, -> { order(:created_at => :desc) }
  scope :featured, -> { limit(10).most_recent_first }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  has_many :dogs
end

app/controllers/application_controller.rb
require_relative Rails.root + 'lib/purge'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def defer_session
    request.session_options[:defer] = true
  end

  def purge(path)
    Rails.logger.tagged "purge" do
      port = Rails.env.test? ? "4567" : "8000"
      http = Net::HTTP.new("localhost", port)
      http.request(Purge.new(path))
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_filter :defer_session, only: %i[index show]

  def index
    @dogs = Dog.includes(:posts).all

    expires_in 0.seconds, must_revalidate: true, "s-maxage": 10.minutes
    fresh_when @dogs, public: true
  end

  def show
    @dog = Dog.find(params[:id])

    response.headers['X-ESI'] = 'true'

    expires_in 0.seconds, must_revalidate: true, "s-maxage": 10.minutes
    fresh_when @dog, public: true
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "marketing"
  before_filter :defer_session, only: %i[index about]

  def index
    @featured_posts = Post.featured

    if user_signed_in?
      redirect_to timeline_path
    else
      expires_in 0.seconds, must_revalidate: true, "s-maxage": 10.minutes
      fresh_when @featured_posts, public: true, template: 'home/index'
    end
  end

  def about
    if Rails.env.test?
      # Rails doesn't send Set-Cookie for every request in test, but it does in dev/prod.
      session[:garbage_to_test_varnish_config] = "true"
    end

    expires_in 60.minutes, public: true, must_revalidate: true, "s-maxage": 24.hours
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :defer_session, only: %i[index show]

  def index
    @posts = current_dog.posts.most_recent_first

    expires_in 0.seconds, must_revalidate: true, "s-maxage": 10.minutes
    if stale?(@posts, public: true)
      render :layout => request.headers['X-ESI'].blank?
    end
  end

  def show
    @post = current_dog.posts.find(params[:id])

    expires_in 0.seconds, must_revalidate: true, "s-maxage": 10.minutes
    fresh_when @post, public: true
  end

  def create
    dog = current_user.dogs.find(params[:dog_id])
    dog.posts.create(post_params)

    purge(dog_posts_path(dog))

    redirect_to dog_path(dog)
  end

  private

  def current_dog
    @dog ||= Dog.where(id: params[:dog_id]).first
  end

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  def show
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown_renderer.render(text).html_safe
  end

  def markdown_renderer
    @markdown_renderer if defined? @markdown_renderer

    @markdown_renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML.new({}), {})
  end
end

app/views/dogs/index.html.erb
<% @dogs.each do |dog| %>
  <article>
    <%= link_to dog do %>
      <h3><%= dog.name %></h3>
    <% end %>
  </article>
<% end %>

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>

<% if user_signed_in? && current_user == @dog.user %>
  <%= form_for [@dog, @dog.posts.build] do |form| %>
    <%= form.text_area :body, autofocus: true, class: "post_body" %>
    <%= form.button "Save", class: "button" %>
  <% end %>
<% end %>

<% if request.headers['X-Varnish'].present? %>
  <esi:include src="<%= dog_posts_path(@dog) %>" />
<% else %>
  <%= render partial: 'posts/post', collection: @dog.posts.most_recent_first, as: 'post' %>
<% end %>

app/views/home/about.html.erb
<h1>About Doglog</h1>

<p>Doglog is a blog... for your dog! Or dogs! Register today and start posting about what your dog
  has been up to in his or her spare time.</p>

<p>Follow the adventures of your friends' dogs, and share your dogs' adventures with them. The
  possibilities are endless!</p>

<p>Doglog is demo software and is provided as-is. Doglog may shut down at any time, without notice.
  Please do not put important, irretrievable information into Doglog. Doglog is a test. Doglog
  loves you.</p>

app/views/home/index.html.erb
<h1>Welcome to Doglog</h1>

<p>The log for your dog!</p>

<%= render @featured_posts %>

app/views/layouts/_navbar.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Doglog', root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li><%= link_to 'Dogs', dogs_path %></li>
      <li><%= link_to 'About', about_path %></li>


      <% if user_signed_in? %>

        <li class="has-dropdown has-form">
          <a href="#">Welcome back, <%= current_user.email %>.</a>
          <ul class="dropdown">
            <% current_user.dogs.each do |dog| %>
              <li><%= link_to dog.name, dog_path(dog) %></li>
            <% end %>
            <li class="divider"></li>

            <li class="alert">
              <%= link_to 'My Account', edit_user_registration_path %>
            </li>
          </ul>
        </li>

        <li class="has-form">
          <div class="row">
            <%= button_to 'Log out', destroy_user_session_path, method: 'delete', class: "button alert" %>
          </div>
        </li>

      <% else %>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li class="has-form">
          <%= link_to 'Sign up', new_user_registration_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doglog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar' %>

  <div class="row">
    <div class="large-12 columns">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doglog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag 'application' %>
</head>
<body>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to 'Doglog', root_path %></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li><%= link_to 'Dogs', dogs_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <li>
          <%= link_to 'Login', new_user_session_path %>
        </li>
        <li class="has-form">
          <%= link_to 'Sign up', new_user_registration_path, class: "button" %>
        </li>
      </ul>
    </section>
  </nav>
  <div class="row">
    <div class="large-12 columns">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/posts/_post.html.erb
<article class="panel">
  <div class="dog-name">
    <%= link_to post.dog.name, post.dog %>
  </div>

  <div class="post-body">
    <%= markdown post.body %>
  </div>

  <p class="posted-at">
    <%= link_to [post.dog, post] do %>
      Posted at <%= l(post.created_at, format: :short) %>
    <% end %>
  </p>
</article>

app/views/posts/index.html.erb
<%= render @posts %>

app/views/posts/show.html.erb
<%= render @post %>

app/views/timelines/show.html.erb
<h1>Timelines#show</h1>
<p>Find me in app/views/timelines/show.html.erb</p>